#Установка и настройка MySQL
#ansible-playbook nginx-jre-playbook.yml -i inventory
#
-
  name: 'Install Nginx'
  hosts: webservers
  become: true
  tasks:
    - name: 'Install nginx'
      yum:
        name: nginx
        state: installed
-
  name: 'Install JRE'
  hosts: webservers
  become: true
  tasks:
    - name: 'Install JRE'
      yum:
        name: jre
        state: installed

  vars:
    # CSS styling for navbar: menu width, failed/missing colors
    nav_width: 200px
    failed_style: 'color:orangered'
    missing_style: 'color:grey;text-decoration:line-through'

  post_tasks:

    - name: 'Mark surviving hosts as successful'
      set_fact:
        job_success: True

    - name: 'Save summary facts under Ansible controller'
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      set_fact:
        date_str: "{{ date }}_{{ hms }}"
        date_str_pretty: "{{ date }} {{ hms_pretty }}"
        kernels_list: '{{ hostvars | json_query(kernel_query) | unique | sort }}'
        success_list: '{{ hostvars | dict2items | json_query(success_query) }}'
        failed_list: '{{ hostvars | dict2items | json_query(failed_query) }}'
        missing_list: '{{ hostvars | dict2items | json_query(missing_query) }}'
      vars:
        kernel_query: "*.ansible_kernel"
        success_query: "[?value.job_success==`true`].key"
        failed_query: "[?value.job_success==`false` && value.missing==`false`].key"
        missing_query: "[?value.missing==`true`].key"
        date: "{{ '%Y-%m-%d' | strftime }}"
        hms_pretty: "{{ '%H:%M:%S' | strftime }}"
        hms: "{{ hms_pretty | replace(':','-') }}"

    - name: 'Save job report'
      delegate_to: localhost
      delegate_facts: True
      run_once: yes
      template:
        dest: "{{ playbook_dir }}job_report.html"